import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SearchBar from '../components/SearchBar'
import CoinList from '../components/CoinList/CoinList'
import axios from 'axios'
import {useState, useEffect} from 'react'

export default function Home({filteredCoins}) {
  const [coins, setCoins] = useState([]);
  console.log(filteredCoins);
  useEffect(() =>{
    axios.get('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false')
    .then(res => {
      setCoins(res.data)
    })
    .catch(err => {
      alert(err.message);
    })
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>CoinBully</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Coin Bully</div>
        <CoinList filteredCoins={coins}/>
      </main>
      {/* <SearchBar /> */}
    </div>
  )
}



// export const getServerSideProps = async () => {
//   const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false')

//   const filteredCoins = await res.json()
  
//   return {
//     props: {filteredCoins}
//   }
// } 